"""vacationvm-dns — a dependency-free, stateless Porkbun DNS reconciler.

The whole tool is deliberately written against the Python standard library
only (``urllib``, ``ssl``, ``json``, ``dataclasses``). It is a *control-plane*
helper that runs at ``colmena apply`` time (as a systemd one-shot on the
target host) and pushes a **declared** set of DNS records to Porkbun. It keeps
no state of its own: every run fetches the live zone, diffs it against the
desired set, and converges. The desired set is generated by Nix from the
``vacationvm.services`` declarations, so the source of truth is the flake.

Submodules:

* :mod:`vacationvm_dns.model`   — typed record/plan values (pure data)
* :mod:`vacationvm_dns.plan`    — the pure reconciliation planner
* :mod:`vacationvm_dns.porkbun` — the Porkbun JSON-API client (injectable transport)
* :mod:`vacationvm_dns.cli`     — argument parsing + the reconcile/plan/show verbs
"""

from __future__ import annotations

__all__ = ["__version__"]

__version__ = "0.1.0"
